# permissions for end users to edit sysauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sysauth-editor-role
rules:
- apiGroups:
  - vault.vault.gobins.io
  resources:
  - sysauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.vault.gobins.io
  resources:
  - sysauths/status
  verbs:
  - get
